# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/helm"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/helm"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/k8s"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/pixo-platform"
    target-branch: "dev"
    schedule:
      interval: "daily"

