
name: Argo Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'argo/**'
    branches:
      - dev
      - main
  push:
    paths:
      - '.github/workflows/argo-tests.yaml'
    branches:
      - pipelines

env:
  GCS_BUCKET_NAME: 'pixo-test-bucket'
  NAMESPACE: 'test'
  SA_NAME: 'test-sa'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./argo

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          install-mode: "goinstall"
          args: --timeout=30m
          working-directory: ./argo


  init:
    name: Initialize Cluster and Install Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./argo
    steps:
      - name: Init Test Cluster
        uses: ./.github/workflows/init-cluster
        with:
          namespace: ${{ env.NAMESPACE }}
          argo-events: true
          argo-workflows: true


  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./argo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Tests
        run: |
          go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ needs.init.outputs.gcp-credentials-file }}
          GOOGLE_JSON_KEY: ${{ needs.init.outputs.gcp-credentials-file }}
          GCS_BUCKET_NAME: ${{ env.GCS_BUCKET_NAME }}
          CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
          NAMESPACE: ${{ env.NAMESPACE }}
          SA_NAME: ${{ env.SA_NAME }}

      - name: Check Test Coverage
        run: |
          go install github.com/vladopajic/go-test-coverage/v2@latest
          go-test-coverage -config=./.coverage.yaml
