
name: K8s Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'k8s/**'
    branches:
      - dev
      - main
  push:
    paths:
      - '.github/workflows/k8s-tests.yaml'
    branches:
      - pipelines

env:
  NAMESPACE: 'test'
  SA_NAME: 'test-sa'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./k8s

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          install-mode: "goinstall"
          args: --timeout=30m
          working-directory: ./k8s

  init:
    uses: PixoVR/pixo-golang-server-utilities/.github/workflows/init-cluster.yaml@pipelines

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Tests
        run: |
          make init-env test
        env:
          KUBECONFIG: ${{ needs.init.outputs.kubeconfig }}
          NAMESPACE: ${{ needs.init.outputs.namespace }}

      - name: Check Test Coverage
        run: |
          go install github.com/vladopajic/go-test-coverage/v2@latest
          go-test-coverage -config=./.coverage.yaml

