
name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pixo-platform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          install-mode: "goinstall"
          args: --timeout=30m
          working-directory: ./pixo-platform

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pixo-platform
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Tests
        run: |
          go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
        env:
          GOOGLE_JSON_KEY: '/home/runner/google-key.json'
          GOOGLE_APPLICATION_CREDENTIALS: '/home/runner/google-key.json'
          GCS_BUCKET_NAME: pixo-test-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: .coverage.yaml
