
name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./pixo-platform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          install-mode: "goinstall"
          args: --timeout=30m
          working-directory: ./pixo-platform

      - name: Run Tests
        run: make test

#      - name: Check Test Coverage
#        uses: vladopajic/go-test-coverage@v2
#        with:
#          config: frontend/.coverage.yaml

permissions:
  contents: read
